### ISSUE TITLE
How you people have a running version of the CTZ ?

### ISSUE THREAD

**Issue by breningham** [SIMPATICOProject/citizenpedia#15]
So the Docker version is missing AAC Support. (which is a big thing and needs to be made more stand-out )

So i try to redeploy on bare-metal and nothing i do can make this work... 
first you have problems like: 
https://github.com/SIMPATICOProject/citizenpedia/blob/02383a045da4bb284f3d4f13e53c62ac9e902480/client/app/questionsShow/questionsShow.html#L187

That stops the CTZ from being ran or built, then when you fix it, you realise that the app doesn't work anyway because 
![image](https://user-images.githubusercontent.com/23170786/45516067-e9818f80-b7a1-11e8-92e9-6e561917490f.png)
(you can see it here: https://ctz.sparta.simpatico-project.eu/ )

I followed the instructions in the readme, apart from instead of grunt serve, i used grunt build (was how i found the unfinished div linked above) and use a systemd service to run the ctz.

**Comment by enriquesanz** [comment]
The docker version is not missing AAC support, you must have an instance of AAC running and just change the config file to point to that instance. Since they are too separate components that the right way to do this.

I have just fixed that html tag error, but that error didn't stop qae to start and working right. I tried both versions: docker and standalone, and both works fine for me starting from scratch.

Sorry, but I couldn't be able to reproduce this error you are showing.

**Comment by breningham** [comment]
At the bottom of your readme it says the docker container does not support AAC. 

Maybe it's time to review the docs? 

So far in this project the only component that has worked consistently is the AAC. 

Besides when I tested the docker version I was receiving a error response whenever trying to log in with the AAC. (From the ctz server) maybe I was using an older version but  your documentation supports my findings.

**Comment by enriquesanz** [comment]
The readme literally says:

"Please note that this container does not include AAC for login."

It does not says anywhere that AAC it is not supported. 

"Not included" <> "not supported". If you have an AAC instance running you only have to configure qae properly.
